### PR TITLE
Adds basic art

### PR DESCRIPTION
**Pull request by isacvale**
Creates basic art concepts in an art folder on the root. Files are kept as svgs and sketches are numbered 00 and up.

### CODE REVIEW

**Comment by ndvo** [comment]
Are this alternative sketches or are they representing different states in the app?
- If they represent different states perhaps we should identify them as such.


**From the sketches I'm assuming these requirements:**
- there is a dark mode and a light mode
    - how does the user switches between them?
- there are up to 4 previous operations shown on screen.
    - are these to be stored only in a single session or should we leverage local storage to persist across sessions?
- the result of the current operation is shown above the current operation
- the operations are addition, subtraction, division, multiplication, exponentiation and (square) root.
    - should the root operation work the same as the exponentiation (user provide the number to be rooted and the desired root?)
- is the result displayed in real time or does the user needs to press the equal button?
- is it necessary to have both "(" and ")"?** Perhaps clicking one of them can either add both "({cursor here})" or add the missing one if there is an odd number of them.

**Comment by ndvo** [comment]
This PR closes #1.

You can add "closes #1" to your commit comment to close it automatically when merged.
(You'll have the opportunity to do that when you click the "merge pull request" button)

**Review by ndvo — APPROVED** [review]

**Comment by isacvale** [comment]
> Are this alternative sketches or are they representing different states in the app?

They're a light/dark mode - just an excuse to use useContext. These are initial sketches, though, many of features are left out, including explanations, components states etc. There should also be at least one more page, as an excuse for using Routes.

> **From the sketches I'm assuming these requirements:**
> 
> * there is a dark mode and a light mode

Yes.

>   * how does the user switches between them?

There will be a toggle. These drawings are a minimum so we can start thinking about the project.

> * there are up to 4 previous operations shown on screen.

These things are not set in stone and will be cover in the readme. But there will be up to n (10, 26?) previous operations, whose results can be recalled by pressing a letter shortcut key.

>   * are these to be stored only in a single session or should we leverage local storage to persist across sessions?

I'd love persistency!

> * the result of the current operation is shown above the current operation

Yes.

> * the operations are addition, subtraction, division, multiplication, exponentiation and (square) root.

Yes. That's a proposal, anyway.

>   * should the root operation work the same as the exponentiation (user provide the number to be rooted and the desired root?)

I've been looking at other calculators, and the vast majority don't do that, so I was thing about just leaving it a sqrt. What's your opinion?

> * is the result displayed in real time or does the user needs to press the equal button?

Real time. The = is not a button. I left it in the design to bring that issue up. It can't be a button if calculation is real time, as it should be. But not having an = button might seem weird.

> * is it necessary to have both "(" and ")"?** Perhaps clicking one of them can either add both "({cursor here})" or add the missing one if there is an odd number of them.

The open close with with cursor inside requires a fine control over the input field, which I was not planning on. Tab will move from a group of buttons to the next, like operations, numbers, previous values, and the arrows will choose a particular button. So I'm thinking arrows won't move the cyrsor on the calculation input - I don't think it will be an input!

**Comment by ndvo** [comment]
For us to have a page to navigate to we could allow the user to save the computation (we can use the slot of the equal button for that).
We could than allow the user to visit a page with the saved computations. I'd also add an option to label a past computation and... Use the label in the calculator.

**Pull request merged**
